[package]
name = "ecucamera_engine"
version = "0.1.0"
edition = "2021"

[lib]
name = "ecucamera_engine"
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
